server:
  port: 8081


spring:
  application:
    name: emaildispatcher
  rabbitmq:
      ddresses: ${CLOUDAMQP_URL}
  mail:
    host: ${SMTP_URL}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
